### ISSUE TITLE
Cache instance not found for alias

### ISSUE THREAD

**Issue by botzill** [Bahus/easy_cache#9]
I get this error when trying simple cache  on a class method

```
@ecached()
    def list_collections(self, query=None, as_options=True):
```
```
easy_cache.core.ImproperlyConfigured: Cache instance not found for alias "default-easy-cache"
```

**Comment by Bahus** [comment]
Hi, please make sure that you setup cache instance as described in read me section “Internal caches framework”. 

If you use multi threading app or Flask app in debug mode, see this comment https://github.com/Bahus/easy_cache/issues/7#issuecomment-445538445
